
runs:
  using: composite
  steps:
    - name: Ensure llvm-17
      shell: bash
      working-directory: libcxx
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x ./llvm.sh
        sudo ./llvm.sh 17
    - name: Build
      shell: bash
      working-directory: libcxx
      run: ./build.sh
    - name: Upload Release Artifact
      uses: actions/upload-artifact@v3
      with:
        working-directory: libcxx
        name: release-artifact
        path: "*.rollups.tar.gz"
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ failure() }}
      with:
        limit-access-to-actor: true
