
runs:
  using: composite
  steps:
    - name: Ensure llvm-17
      shell: bash
      working-directory: libcxx
      run: |
        mkdir -p tmp
        apt download binaryen && dpkg -x binaryen*.deb tmp/
        echo $PWD/tmp/usr/bin | tee -a $GITHUB_PATH
        wget https://apt.llvm.org/llvm.sh
        chmod +x ./llvm.sh
        sudo ./llvm.sh 17 2>&1 | (grep -iE 'warning|error|fail|\bnot\b' || true)
        #curl https://github.com/bytecodealliance/wasmtime/releases/download/dev/wasmtime-dev-x86_64-linux.tar.xz \
        #    | tar --strip-components=1 -xvf wasmtime-dev-x86_64-linux/wasmtime

    - name: Preflight checks
      shell: bash
      working-directory: libcxx
      run: |
        clang++-17 --version | head -1
        llvm-config-17 --version
        wasm-dis --version

    - name: Build
      shell: bash
      working-directory: libcxx
      run: ./build.sh

    - name: Test
      shell: bash
      working-directory: libcxx
      run: |
        ls -l staging/
        ./build.sh compile c++ -o main.wasm test/main.cpp src/noops.*
        node src/versions.js main.wasm
        ./build.sh compile c -o stdio.wasm test/stdio.c src/noops.*.c
        node src/versions.js stdio.wasm

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v3
      with:
        working-directory: libcxx
        name: release-artifact
        path: "*.rollups.tar.gz"
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ failure() }}
      with:
        limit-access-to-actor: true
