
runs:
  using: composite
  steps:
    - name: Ensure llvm-17
      shell: bash
      working-directory: libcxx
      run: |
        mkdir -p tmp
        apt download binaryen && dpkg -x binaryen*.deb tmp/
        echo $PWD/tmp/usr/bin | tee -a $GITHUB_PATH
        wget https://apt.llvm.org/llvm.sh
        chmod +x ./llvm.sh
        sudo ./llvm.sh 17 2>&1 | (grep -iE 'warning|error|fail|\bnot\b' || true)
        #curl https://github.com/bytecodealliance/wasmtime/releases/download/dev/wasmtime-dev-x86_64-linux.tar.xz \
        #    | tar --strip-components=1 -xvf wasmtime-dev-x86_64-linux/wasmtime

    - name: Preflight checks
      shell: bash
      working-directory: libcxx
      run: |
        clang++-17 --version | head -1
        llvm-config-17 --version
        wasm-dis --version

    - name: Build
      shell: bash
      working-directory: libcxx
      run: ./build.sh

    - name: Test
      shell: bash
      working-directory: libcxx
      run: |
        ls -l staging/ *.tar.gz
        echo artifact_name=$(date "+%Y%m%d").rollups.libcxx-wasm32 | tee -a $GITHUB_ENV | tee -a $GITHUB_STEP_SUMMARY
        export CC=clang-17 CXX=clang++-17
        ./staging/bin/w32c++-17 test/main.cpp -o main.cxx.wasm
        ./staging/bin/w32c++-17 test/stdio.cpp -o stdio.cxx.wasm
        ./staging/bin/w32cc-17 test/stdio.c -o stdio.c.wasm
        ./staging/bin/w32c++-17 test/stdio.cpp -o stdio.cxx.capture.wasm -lqwasi-capture
        ./staging/bin/w32cc-17 test/stdio.c -o stdio.c.capture.wasm -lqwasi-capture
        for x in *.wasm ; do
          echo "### $x" ; echo '```' ; ./staging/bin/w32info $x ; echo '```' ;
        done | tee -a $GITHUB_STEP_SUMMARY


    - name: Upload Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.artifact_name }}
        path: libcxx/staging/
        compression-level: 9

    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   #if: ${{ failure() }}
    #   with:
    #     limit-access-to-actor: true
